backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "product"
    label: "Product"
    folder: "src/pages/products"
    create: true
    slug: "index"
    media_folder: ''
    public_folder: ''
    path: '{{name}}/index'
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Short description", name: "description-short", widget: "text"}
      - {label: "Long description", name: "description-long", widget: "markdown"}
      - {label: "Image", name: "image", widget: image}
      - {label: "Price", name: "price", widget: "number", value_type: "float"}

