backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files: 
    # Index
      - file: "src/pages/index-about.md"
        label: "Index: O fundacji"
        name: "index-about"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/index-coffee.md"
        label: "Index: Manufaktura kawy"
        name: "index-coffee"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/index-shop.md"
        label: "Index: Sklep"
        name: "index-shop"
        fields:
    # About
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/about/about-mission.md"
        label: "O fundacji: Misja"
        name: "about-mission"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/about/about-managment.md"
        label: "O fundacji: Zarząd"
        name: "about-managment"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/about/about-barbara.md"
        label: "O fundacji: Barbara"
        name: "about-barbara"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/about/about-man.md"
        label: "O fundacji: Imie Naziwko"
        name: "about-man"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      # Reszta
      - file: "src/pages/contact/index.md"
        label: "Kontakt"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/shop/info-cart.md"
        label: "Informajce w koszyku"
        name: "info-cart"
        fields: 
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/shop/info-products.md"
        label: "Informajce o produktach"
        name: "info-products"
        fields: 
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "posts"
    label: "Posts"
    folder: "src/pages/blog"
    create: true
    slug: "index"
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Image", name: "featuredimage", widget: image}